############# English navigation ##############

# main menu
[[main]]
name = "Games"
url = "/games"
weight = 1

[[main]]
name = "Wishlist"
url = "/wishlist"
weight = 2

[[main]]
name = "Methodology"
url = "/methodology"
weight = 3

[[main]]
name = "Technology"
url = "/technology"
weight = 4

[[main]]
name = "Philosophy"
url = "/philosophy"
weight = 5

[[main]]
name = "Blog"
url = "/blog"
weight = 6

[[main]]
name = "Contacts"
url = "/contact"
weight = 7


# footer menu
[[footer]]
name = "Games"
url = "/games"
weight = 1

[[footer]]
name = "Wishlist"
url = "/wishlist"
weight = 2

[[footer]]
name = "Methodology"
url = "/methodology"
weight = 3

[[footer]]
name = "Technology"
url = "/technology"
weight = 4

[[footer]]
name = "Philosophy"
url = "/philosophy"
weight = 5

[[footer]]
name = "Blog"
url = "/blog"
weight = 6

[[footer]]
name = "Contacts"
url = "/contact"
weight = 7

[[footer]]
name = "Privacy"
url = "/privacy-policy"
weight = 8
