/**
 * Regenerates assets/css/generated-theme.css from data/theme.json.
 *
 *   npm run theme
 *
 * The Hugoplate module ships its own generated-theme.css with the stock
 * palette; the project copy shadows it, which is why this has to be rerun
 * after editing data/theme.json.
 */

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const theme = JSON.parse(fs.readFileSync(path.join(root, "data", "theme.json"), "utf8"));
const output = path.join(root, "assets", "css", "generated-theme.css");

const kebab = (value) => value.replace(/_/g, "-");
const fontName = (value) => value.replace(/\+/g, " ").replace(/:[^:]+/g, "");

const lines = [];
const push = (...items) => lines.push(...items);

const colorVars = (colors, prefix) =>
  Object.entries(colors).flatMap(([group, entries]) =>
    Object.entries(entries).map(([name, value]) => `  --color-${prefix}${kebab(name)}: ${value};`),
  );

push("/**");
push(' * Auto-generated from "data/theme.json"');
push(" * DO NOT EDIT THIS FILE MANUALLY");
push(" * Run: npm run theme");
push(" */");
push("");
push("@theme {");
push("  /* === Colors === */");
push(...colorVars(theme.colors.default, ""));
push("");
push("  /* === Darkmode Colors === */");
push(...colorVars(theme.colors.darkmode, "darkmode-"));
push("");
push("  /* === Font Families === */");
const { font_family: family, font_size: size } = theme.fonts;
push(`  --font-primary: ${fontName(family.primary)}, ${family.primary_type};`);
push(`  --font-secondary: ${fontName(family.secondary)}, ${family.secondary_type};`);
push("");
push("  /* === Font Sizes === */");

const base = Number(size.base);
const scale = Number(size.scale);
push(`  --text-base: ${base}px;`);
push(`  --text-base-sm: ${base * 0.8}px;`);
for (let heading = 6; heading >= 1; heading--) {
  const rem = Number(Math.pow(scale, 7 - heading).toFixed(6));
  push(`  --text-h${heading}: ${rem}rem;`);
  push(`  --text-h${heading}-sm: ${Number((rem * 0.9).toFixed(6))}rem;`);
}
push("}");
push("");

fs.writeFileSync(output, lines.join("\n"));
console.log(`wrote ${path.relative(root, output)}`);
